- hosts: 192.168.237.5 
  tasks:
   - include_vars: "file.py"
   - package:
       name: "/root/Desktop/jdk-8u171-linux-x64.rpm"       
       state: present
   - lineinfile:
       path: "/root/.bashrc"
       line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/\nexport PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH\n"
   - command: "bash"


   - command: "rpm -i /root/Desktop/hadoop-1.2.1-1.x86_64.rpm --force"
   - replace:
       path: "/etc/hadoop/hdfs-site.xml"
       regexp: "<configuration>"
       replace: "<configuration>\n<property>\n<name>dfs.data.dir</name>\n<value>{{ file_dn }}</value>\n</property>\n"

   - replace:
       path: "/etc/hadoop/core-site.xml"
       regexp: "<configuration>"
       replace: "<configuration>\n<property>\n<name>fs.default.name</name>\n<value>hdfs://{{ip_dn}}:9001</value>\n</property>\n"
 
   - command: "iptables -F"
   - command: "setenforce 0"
   - command: "hadoop-daemon.sh start datanode"
  
   - command: "jps"
     register: x
   - debug:
       msg: "{{ x }}"     
   - debug: 

       msg: "Your Service is STARTED!!!!!!!!!!!!!!!!!!!!!ENJOY !!!!!!!!!!!"
     when: x.rc == 0 



- hosts: 192.168.237.3
  tasks:
   - include_vars: "file.py"
   - package:
       name: "/root/Desktop/jdk-8u171-linux-x64.rpm"       
       state: present
   - lineinfile:
       path: "/root/.bashrc"
       line: "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/\nexport PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH\n"
   - command: "bash"
   - command: "rpm -i /root/Desktop/hadoop-1.2.1-1.x86_64.rpm --force"

   - replace:
       path: "/etc/hadoop/hdfs-site.xml"
       regexp: "<configuration>"
       replace: "<configuration>\n<property>\n<name>dfs.name.dir</name>\n<value>{{file_nn}}</value>\n</property>\n"

   - replace:
       path: "/etc/hadoop/core-site.xml"
       regexp: "<configuration>"
       replace: "<configuration>\n<property>\n<name>fs.default.name</name>\n<value>hdfs://{{ ip_nn }}:9001</value>\n</property>\n"
   - file:
       path: "{{ file_nn }}"
       state: directory 
       mode: 0755
   - command: "iptables -F"
   - command: "setenforce 0"
   - command: "hadoop namenode -format -force"
   - command: "hadoop-daemon.sh start namenode"
   - command: "jps"
     register: p
   - debug:
       msg: "{{ p }}"  
   - debug: 

       msg: "Your Service is STARTED!!!!!!!!!!!!!!!!!!!!!ENJOY !!!!!!!!!!!"
     when: p.failed == false 
  tags: "data"  
